### ISSUE TITLE
QRedshitf doesn't work after screen lock

### ISSUE THREAD

**Issue by adrianlopezgalera** [raphaelquintao/QRedshiftCinnamon#48]
Hi!

I'm using Linux Mint 20.3. I updated QRedshitf to the latest version (1.7.2) and I detected a bug still present from previous versions. When the screen locks (by time or user choice) and the desktop loads again after entering the password, QRedshitf appears enabled in the taskbar but it doesn't work. Deactivating and re-activating it (with the toggle button) is required for it to reapply the existing settings.

Regards.

**Comment by raphaelquintao** [comment]
I'll take a look at it. Never noticed before...
Thanks for the report.

**Comment by raphaelquintao** [comment]
For me it works normal, I lock the screen and it works even on the lock screen.

**Comment by adrianlopezgalera** [comment]
> For me it works normal, I lock the screen and it works even on the lock screen.

Hello, I just realized that this bug was already reported (#3). I forgot to say that it happened when changing users. Perhaps I had thought that it also happened with normal blocking without noticing that I switch user several times.

Regards.

**Comment by eli-damon** [comment]
I've noticed the same problem on Mint 21. Thanks.

**Comment by Machion** [comment]
I have the same problem for a very long time now, on Manjaro (22)

**Comment by raphaelquintao** [comment]
I think this has been fixed in the new versions, can anyone confirm please?
I just released the version 2.0.0 by the way.

**Comment by adrianlopezgalera** [comment]
Hello. I have tested the new version on my laptop with Linux Mint 20.3, connected via HDMI. It does not activate and does not work in any way. My system has become unusable because it is so painful to look at the screen.

Regards.

**Comment by raphaelquintao** [comment]
The version 2.0.0 was reverted back on the repository. 
For now, if you want the latest version maintained by me you can follow these steps:

1. Download zip from [qredshift@quintao_2.0.0.zip](https://github.com/raphaelquintao/QRedshiftCinnamon/releases/download/v2.0.0/qredshift@quintao_2.0.0.zip).
2. Extract .zip archive to `~/.local/share/cinnamon/applets`.
3. Enable the applet in Cinnamon settings

**Comment by raphaelquintao** [comment]
Can you try the new version and check if it works?

Copy and paste that on terminal to update:
```shell
curl https://github.com/raphaelquintao/QRedshiftCinnamon/raw/master/install.sh -sSfL | bash 
```

**Comment by adrianlopezgalera** [comment]
Hello again. I just installed the new version (thanks for providing a script) and it still doesn't work. Does your program keep a error log? If you give me some guidance, I could provide you with a bug report.

Regards.

**Comment by munkmode** [comment]
Hello @raphaelquintao 

I'm experiencing the same bug on my system. After the screen locks due to inactivity, and when I log back in the red tint is off and I have to tap Ctrl+Alt+P twice to toggle it off then back on for it to come back.

Linux Mint 22.1
Cinnamon 6.4.6
kernel 6.8.0-52-generic

I wasn't experiencing this bug on Mint 22, only started happening after updating to 22.1.

Thanks for all your work put into QRedShift, phenomenal and essential app for me.
